AddonId: 62ac4052-e08a-4a1a-b70a-c2c0c3673bb9
Packages:
  - ReleaseDate: "2024-12-16"
    PackageUrl: https://github.com/ecenshu/HumbleKeysLibrary/releases/download/0.3.5-alpha89/HumbleKeysLibrary_0.3.5-alpha89.pext
    Changelog: |2+
  - Version: 0.3.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2024-10-04
    PackageUrl: https://github.com/ecenshu/HumbleKeysLibrary/releases/download/v0.3.4/HumbleKeysLibrary.pext
